apiVersion: v1
kind: Service
metadata:
  name: &service-name docker
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: http
      port: 8080
      nodePort: 30902 # nodePort has to be in range 30000-32767
      protocol: TCP
